<template>

  <div>
    <nav-bar></nav-bar>
    <div>
      <label for="ImageTitle">Title : </label>
      <input v-model="Title" id="ImageTitle" placeholder="Please give it a title">
    </div>
    <div>  
    <input type="file" id="goatFile" :disabled="uploadDisabled" accept="image/*" @change="stageFiles($event.target.files)">
    </div>
    <div>
    <button v-on:click="uploadYoGoat()">Push the Goat Out</button>
    </div>
    <div class="progress-bar" :style="{ width: progressUpload + '%'}">{{ progressUpload }}%</div>
  </div>

</template>

<script>
import { auth, storage, db } from '../firebase-init'
// import { EventBus } from '../eventbus'

export default {
  name: 'FileUploader',
  data () {
    return {
      progressUpload: 0,
      file: File,
      uploadTask: '',
      downloadURL: '',
      stagedFiles: [],
      uploadDisabled: false,
      Title: ''
    }
  },
  methods: {
    uploadYoGoat () {
      console.log('Thanks for Trying mate. I appreciate yall : ')
      // Check if Title is empty string if so reject
      if (this.$data.Title === '') {
        alert('You need a Title. We said Please!')
        return
      }
      var uploaderName = auth.currentUser().displayName
      var imageID = this.saveFileDetails(this.$data.Title, uploaderName)
      var upFile = this.$data.stagedFiles[0]
      var metadata = {
        customMetadata: {
          Title: this.$data.Title,
          ID: imageID,
          Uploader: uploaderName
        }
      }
      // Upload the file
      this.upload(upFile, metadata)
    },
    saveFileDetails (title, user) {
      // use  DB object. Create an ID then return it. We use a ref to a 'goats' path then push some data in
      var newPostRef = db.ref('goats').push({
        Title: title,
        Uploader: user
      })
      // Get the unique key generated by push()
      var postId = newPostRef.key
      return postId
    },
    stageFiles (fileList) {
      Array.from(Array(fileList.length).keys()).map(x => {
        // this.upload()
        // at the minute they could stage a number of files. I think we should disable the form
        this.stagedFiles.push(fileList[x])
        this.$data.uploadDisabled = true
      })
    },
    upload (file, meta) {
      this.uploadTask = storage.ref('goats/' + file.name).put(file, meta)
      this.uploadTask.then(snapshot => {
        this.downloadURL = this.uploadTask.snapshot.downloadURL
        // need to work this emit bit out as this is useful info to have
        this.$emit('url', this.downloadURL)
      })
    }
  },
  watch: {
    uploadTask: function () {
      this.uploadTask.on('state_changed', sp => {
        this.progressUpload = Math.floor(sp.bytesTransferred / sp.totalBytes * 100)
      })
    }
  }
}
</script>

<style>
.progress-bar {
  margin: 10px 0;
}
</style>
